name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: build      # If you have a separate 'build' workflow in the same repo
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: docker pull sakthipachaiyappan78/swiggy-clone:latest

      - name: Scan Image with Trivy
        run: trivy image sakthipachaiyappan78/swiggy-clone:latest > trivyimagedeploy.txt

      - name: Deploy Docker Container
        run: |
          docker stop swiggy-clone || true
          docker rm swiggy-clone || true
          docker run -d --name swiggy-clone -p 3000:3000 sakthipachaiyappan78/swiggy-clone:latest
