deploy:
   needs: build
   runs-on: self-hosted
   steps:
      - name: docker pull image
        run: docker pull sakthipachaiyappan78/swiggy-clone:latest
      - name: Image scan
        run: trivy image sakthipachaiyappan78/swiggy-clone:latest > trivyimagedeploy.txt
      - name: Deploy to container
        run: docker run -d --name swiggy-clone -p 3000:3000 sakthipachaiyappan78/swiggy-clone:latest
